---
title: "Flashsale GA"
author: "Yuhan Wu"
date: "3/28/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

```{r}
library(genalg)
library(ggplot2)
library(tidyverse)
library(animation)

dataset <- data.frame(item = c("pocketknife", "beans", "potatoes", "unions", 
    "sleeping bag", "rope", "compass"), survivalpoints = c(10, 20, 15, 2, 30, 
    10, 30), weight = c(1, 5, 20, 1, 7, 5, 1))
weightlimit <- 20

chromosome = c(1, 0, 0, 1, 1, 0, 0)
dataset[chromosome == 1, ]

cat(chromosome %*% dataset$survivalpoints)

evalFunc <- function(x) {
    current_solution_survivalpoints <- x %*% dataset$survivalpoints
    current_solution_weight <- x %*% dataset$weight
    if (current_solution_weight > weightlimit) 
        return(0) else return(-current_solution_survivalpoints)
}

iter = 100
GAmodel <- rbga.bin(size = 7, popSize = 200, iters = iter, mutationChance = 0.03, 
    elitism = T, evalFunc = evalFunc)
cat(summary(GAmodel))

solution = c(1, 1, 1, 1, 1, 0, 1)
dataset[solution == 1, ]


cat(paste(solution %*% dataset$survivalpoints, "/", sum(dataset$survivalpoints)))


```

```{r}
animate_plot <- function(x) {
    for (i in seq(1, iter)) {
        temp <- data.frame(Generation = c(seq(1, i), seq(1, i)), Variable = c(rep("mean", 
            i), rep("best", i)), Survivalpoints = c(-GAmodel$mean[1:i], -GAmodel$best[1:i]))

        pl <- ggplot(temp, aes(x = Generation, y = Survivalpoints, group = Variable, 
            colour = Variable)) + geom_line() + scale_x_continuous(limits = c(0, 
            iter)) + scale_y_continuous(limits = c(0, 110)) + geom_line(y = max(temp$Survivalpoints), 
            lty = 2) + annotate("text", x = 1, y = max(temp$Survivalpoints) + 
            2, hjust = 0, size = 3, color = "black", label = paste("Best solution:", 
            max(temp$Survivalpoints))) + scale_colour_brewer(palette = "Set1") 

        print(pl)
    }
}

# in order to save the animation

saveGIF(animate_plot(), movie.name = "animation2.gif", convert = "magick",interval = 0.1, outdir = getwd())
```

