---
title: "Simulation2"
author: "Yuhan Wu"
date: "3/31/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
set.seed(122)                                                     # Set seed for reproducibility

object_ranking <- tibble(item = c("P1", "P2", "P3", "P4", 
    "P5", "P6", "P7", "P8", "P9", "P10", "P11", "P12", "P13", "P14", "P15", "P16","P17", "P18", "P19","P20","P21",
    "P22","P23","P24","P25","P26","P27","P28","P29","P30","P31","P32","P33","P34","P35","P36","P37"), 
    discount = c(0.37, 0.36, 0.35, 0.34, 0.33,0.32, 0.31, 0.30, 0.29, 0.28, 0.27, 0.26, 0.25, 0.24, 0.23, 0.22, 0.21, 0.20, 0.19, 0.18, 0.17, 0.16, 0.15, 0.14, 0.13, 0.12, 0.11, 0.10, 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1), 
    price = c(1300,1700,1600,1500,2000,2100,2200,2500,2800,2900,3000,1800,900,800,500,400,200,800,600,3000,2800,3400,2800,1500,1600,1700,1800,1900,2000,900,800,700,600,500,400,1300,1200),
    quantity = c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37))

object_ranking %>%
  mutate(rankings = 3*discount+2*price+ 3/quantity) %>%
  arrange(desc(rankings)) 
  
```


```{r}
floor_prob <- tibble(
  position = c(1,2,3,4,5,6,7,8,9,10,
                    11,12,13,14,15,16,17,
                    18,19,20,21,22,23,24,
                    25,26,27,28,29,30,31,
                    32,33,34,35,36,37,38,39,40),
  
  distance_Entr = c(8,11,8,10,8,6,11,4,6,7,
                    11,12,6,14,4,9,17,
                    18,19,20,21,7,9,24,
                    25,13,27,28,29,13,22,
                    12,15,13,23,23,22,23,22,23),
  
  distance_Cash = c(20,6,17,16,18,6,7,13,21,10,
                    11,12,4,14,4,7,17,
                    18,19,12,5,4,8,24,
                    25,6,14,28,14,7,13,
                    15,12,2,35,18,7,17,39,21),
  
  hallway_Wide = c(11,2,3,7,9,6,7,21,9,17,
                    18,4,5,8,15,16,17,
                    18,19,6,21,7,5,14,
                    19,15,27,28,7,9,19,
                    10,11,12,23,11,20,21,16,18),
  
  previous_dist = c(0,0,0,0,0,
                    0,0,0,0,0,
                    0,0,0,0,0,
                    0,0,0,0,0,
                    0,0,0,0,0,
                    0,0,0,0,0,
                    0,0,0,0,0,
                    0,0,0,0,0),
  
 previous_dist1 = c(0,0,0,0,0,
                    0,0,0,0,0,
                    0,0,0,0,0,
                    0,0,0,0,0,
                    0,0,0,0,0,
                    0,0,0,0,0,
                    0,0,0,0,0,
                    0,0,0,0,0),
         
 previous_dist2 = c(0,0,0,0,0,
                    0,0,0,0,0,
                    0,0,0,0,0,
                    0,0,0,0,0,
                    0,0,0,0,0,
                    0,0,0,0,0,
                    0,0,0,0,0,
                    0,0,0,0,0),
         
 previous_dist3 = c(0,0,0,0,0,
                    0,0,0,0,0,
                    0,0,0,0,0,
                    0,0,0,0,0,
                    0,0,0,0,0,
                    0,0,0,0,0,
                    0,0,0,0,0,
                    0,0,0,0,0),
 
 previous_dist4 = c(0,0,0,0,0,
                    0,0,0,0,0,
                    0,0,0,0,0,
                    0,0,0,0,0,
                    0,0,0,0,0,
                    0,0,0,0,0,
                    0,0,0,0,0,
                    0,0,0,0,0),
 
 previous_dist5 = c(0,0,0,0,0,
                    0,0,0,0,0,
                    0,0,0,0,0,
                    0,0,0,0,0,
                    0,0,0,0,0,
                    0,0,0,0,0,
                    0,0,0,0,0,
                    0,0,0,0,0),
 
 previous_dist7 = c(0,0,0,0,0,
                    0,0,0,0,0,
                    0,0,0,0,0,
                    0,0,0,0,0,
                    0,0,0,0,0,
                    0,0,0,0,0,
                    0,0,0,0,0,
                    0,0,0,0,0),
 
 previous_dist8 = c(0,0,0,0,0,
                    0,0,0,0,0,
                    0,0,0,0,0,
                    0,0,0,0,0,
                    0,0,0,0,0,
                    0,0,0,0,0,
                    0,0,0,0,0,
                    0,0,0,0,0),
 
 previous_dist9 = c(0,0,0,0,0,
                    0,0,0,0,0,
                    0,0,0,0,0,
                    0,0,0,0,0,
                    0,0,0,0,0,
                    0,0,0,0,0,
                    0,0,0,0,0,
                    0,0,0,0,0),
 
 previous_dist10 = c(0,0,0,0,0,
                    0,0,0,0,0,
                    0,0,0,0,0,
                    0,0,0,0,0,
                    0,0,0,0,0,
                    0,0,0,0,0,
                    0,0,0,0,0,
                    0,0,0,0,0))

```

```{r}


floor_innit <- floor_prob %>%
  mutate(demg_prob = 0.7*((5/distance_Entr) +(3/distance_Cash)+ (7/hallway_Wide)-20*(-previous_dist/10))) %>%
    arrange(position)

dmg_prob1 <- floor_innit %>%
  summarise(position,demg_prob) %>%
  pull(demg_prob)

data1 <- matrix(dmg_prob1, nrow = 5, ncol = 8)
heatmap(data1,Rowv = NA, Colv = NA)  
```

```{r}
floor_2 <- floor_innit %>%
  mutate(previous_dist1 = c(0,14,12,7,12,
                    7,10,12,13,1,
                    9,8,21,18,17,
                    6,4,21,22,23,
                    7,23,16,14,17,
                    18,34,23,10,10,
                    8,5,3,6,8,
                    19,18,15,12,10)) %>%
   mutate(demg_prob = 0.7*((5/distance_Entr) +(3/distance_Cash)+ (7/hallway_Wide)-
                             20*(-(previous_dist1+ previous_dist2+ previous_dist3+ previous_dist4)/10))) %>%
    arrange(position)

dmg_prob2 <- floor_2 %>%
  summarise(position,demg_prob) %>%
  pull(demg_prob)

data2 <- matrix(dmg_prob2, nrow = 5, ncol = 8)
heatmap(data2,Rowv = NA, Colv = NA)  
```



```{r}
data <- matrix(rnorm(110, 0, 10), nrow = 10, ncol = 11)           # Create example data

colnames(data) <- paste0("col", 1:11)   # Column names

rownames(data) <- paste0("row", 1:10)                             # Row names

heatmap(data,Rowv = NA, Colv = NA)    
```

